-- MySQL Script generated by MySQL Workbench
-- Sat Jul  3 16:17:31 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema g-nom_dev
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema g-nom_dev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `g-nom_dev` DEFAULT CHARACTER SET utf8 ;
USE `g-nom_dev` ;

-- -----------------------------------------------------
-- Table `g-nom_dev`.`taxon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `g-nom_dev`.`taxon` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ncbiTaxonID` INT NOT NULL,
  `scientificName` VARCHAR(400) NOT NULL,
  `imagePath` VARCHAR(400) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `g-nom_dev`.`assembly`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `g-nom_dev`.`assembly` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `taxonID` INT NOT NULL,
  `name` VARCHAR(400) NOT NULL,
  `path` VARCHAR(400) NOT NULL,
  `additionalFilesPath` VARCHAR(400) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `assemblyName_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `taxonID_idx` (`taxonID` ASC) VISIBLE,
  CONSTRAINT `taxonID`
    FOREIGN KEY (`taxonID`)
    REFERENCES `g-nom_dev`.`taxon` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `g-nom_dev`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `g-nom_dev`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `role` VARCHAR(20) NOT NULL DEFAULT 'admin',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `g-nom_dev`.`assemblyStatistic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `g-nom_dev`.`assemblyStatistic` (
  `id` INT NOT NULL,
  `assemblyID` INT NOT NULL,
  `path` VARCHAR(400) NOT NULL,
  `additionalFilesPath` VARCHAR(400) NULL,
  PRIMARY KEY (`id`),
  INDEX `assemblyStatisticsID_idx` (`assemblyID` ASC) VISIBLE,
  CONSTRAINT `assemblyStatisticsID`
    FOREIGN KEY (`assemblyID`)
    REFERENCES `g-nom_dev`.`assembly` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `g-nom_dev`.`assemblyStatisticGeneralInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `g-nom_dev`.`assemblyStatisticGeneralInfo` (
  `id` INT NOT NULL,
  `assemblyStatisticID` INT NOT NULL,
  `key` VARCHAR(400) NOT NULL,
  `value` VARCHAR(400) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `assemblyStatisticsInfoID_idx` (`assemblyStatisticID` ASC) VISIBLE,
  CONSTRAINT `assemblyStatisticsInfoID`
    FOREIGN KEY (`assemblyStatisticID`)
    REFERENCES `g-nom_dev`.`assemblyStatistic` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `g-nom_dev`.`assemblyStatisticsPlot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `g-nom_dev`.`assemblyStatisticsPlot` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `assemblyStatisticID` INT NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `path` VARCHAR(400) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `assemblyStatiscitsPlotID_idx` (`assemblyStatisticID` ASC) VISIBLE,
  CONSTRAINT `assemblyStatiscitsPlotID`
    FOREIGN KEY (`assemblyStatisticID`)
    REFERENCES `g-nom_dev`.`assemblyStatistic` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `g-nom_dev`.`analysis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `g-nom_dev`.`analysis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `assemblyID` INT NOT NULL,
  `type` VARCHAR(50) NOT NULL,
  `path` VARCHAR(400) NOT NULL,
  `additionalFilesPath` VARCHAR(400) NULL,
  `description` VARCHAR(2000) NULL,
  PRIMARY KEY (`id`),
  INDEX `assemblyAnalysisID_idx` (`assemblyID` ASC) VISIBLE,
  CONSTRAINT `assemblyAnalysisID`
    FOREIGN KEY (`assemblyID`)
    REFERENCES `g-nom_dev`.`assembly` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `g-nom_dev`.`busco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `g-nom_dev`.`busco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `analysisID` INT NOT NULL,
  `completeSingle` INT NOT NULL,
  `completeDuplicated` INT NOT NULL,
  `fragmented` INT NOT NULL,
  `missing` INT NOT NULL,
  `total` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `analysisID_UNIQUE` (`analysisID` ASC) VISIBLE,
  CONSTRAINT `analysisBuscoID`
    FOREIGN KEY (`analysisID`)
    REFERENCES `g-nom_dev`.`analysis` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `g-nom_dev`.`milts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `g-nom_dev`.`milts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `analysisID` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `analysisID_UNIQUE` (`analysisID` ASC) VISIBLE,
  CONSTRAINT `analysisMiltsID`
    FOREIGN KEY (`analysisID`)
    REFERENCES `g-nom_dev`.`analysis` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `g-nom_dev`.`taxonGeneralInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `g-nom_dev`.`taxonGeneralInfo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `taxonID` INT NOT NULL,
  `key` VARCHAR(400) NOT NULL,
  `value` VARCHAR(2000) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `taxonIDgeneralInfo_idx` (`taxonID` ASC) VISIBLE,
  CONSTRAINT `taxonIDgeneralInfo`
    FOREIGN KEY (`taxonID`)
    REFERENCES `g-nom_dev`.`taxon` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `g-nom_dev`.`fcat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `g-nom_dev`.`fcat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `analysisID` INT NOT NULL,
  `m1_similar` INT NOT NULL,
  `m1_dissimilar` INT NOT NULL,
  `m1_duplicated` INT NOT NULL,
  `m1_missing` INT NOT NULL,
  `m1_ignored` INT NOT NULL,
  `m2_similar` INT NOT NULL,
  `m2_dissimilar` INT NOT NULL,
  `m2_duplicated` INT NOT NULL,
  `m2_missing` INT NOT NULL,
  `m2_ignored` INT NOT NULL,
  `m3_similar` INT NOT NULL,
  `m3_dissimilar` INT NOT NULL,
  `m3_duplicated` INT NOT NULL,
  `m3_missing` INT NOT NULL,
  `m3_ignored` INT NOT NULL,
  `m4_similar` INT NOT NULL,
  `m4_dissimilar` INT NOT NULL,
  `m4_duplicated` INT NOT NULL,
  `m4_missing` INT NOT NULL,
  `m4_ignored` INT NOT NULL,
  `total` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `analysisID_UNIQUE` (`analysisID` ASC) VISIBLE,
  CONSTRAINT `analysisFcatID`
    FOREIGN KEY (`analysisID`)
    REFERENCES `g-nom_dev`.`analysis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `g-nom_dev`.`repeatmasker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `g-nom_dev`.`repeatmasker` (
  `id` INT NOT NULL,
  `analysisID` INT NOT NULL,
  `retroelements` INT NOT NULL,
  `retroelements_length` INT NOT NULL,
  `dna_transposons` INT NOT NULL,
  `dna_transposons_length` INT NOT NULL,
  `rolling_circles` INT NOT NULL,
  `rolling_circles_length` INT NOT NULL,
  `unclassified` INT NOT NULL,
  `unclassified_length` INT NOT NULL,
  `small_rna` INT NOT NULL,
  `small_rna_length` INT NOT NULL,
  `satellites` INT NOT NULL,
  `satellites_length` INT NOT NULL,
  `simple_repeats` INT NOT NULL,
  `simple_repeats_length` INT NOT NULL,
  `low_complexity` INT NOT NULL,
  `low_complexity_length` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `analysisID_UNIQUE` (`analysisID` ASC) VISIBLE,
  CONSTRAINT `analysisRepeatmaskerID`
    FOREIGN KEY (`analysisID`)
    REFERENCES `g-nom_dev`.`analysis` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `g-nom_dev`.`annotation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `g-nom_dev`.`annotation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `assemblyID` INT NOT NULL,
  `path` VARCHAR(400) NOT NULL,
  `additionalFilesPath` VARCHAR(400) NULL,
  `description` VARCHAR(2000) NULL,
  PRIMARY KEY (`id`),
  INDEX `assemblyAnnotationID_idx` (`assemblyID` ASC) VISIBLE,
  CONSTRAINT `assemblyAnnotationID`
    FOREIGN KEY (`assemblyID`)
    REFERENCES `g-nom_dev`.`assembly` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `g-nom_dev`.`bookmark`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `g-nom_dev`.`bookmark` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `userID` INT NOT NULL,
  `assemblyID` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `userIDSubscription_idx` (`userID` ASC) VISIBLE,
  INDEX `assemblyIDSubscription_idx` (`assemblyID` ASC) VISIBLE,
  CONSTRAINT `userIDSubscription`
    FOREIGN KEY (`userID`)
    REFERENCES `g-nom_dev`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `assemblyIDSubscription`
    FOREIGN KEY (`assemblyID`)
    REFERENCES `g-nom_dev`.`assembly` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `g-nom_dev`.`proteins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `g-nom_dev`.`proteins` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `annotationID` INT NOT NULL,
  `path` VARCHAR(400) NOT NULL,
  `additionalFilesPath` VARCHAR(400) NULL,
  PRIMARY KEY (`id`),
  INDEX `annotationIDproteins_idx` (`annotationID` ASC) VISIBLE,
  CONSTRAINT `annotationIDproteins`
    FOREIGN KEY (`annotationID`)
    REFERENCES `g-nom_dev`.`annotation` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `g-nom_dev`.`assemblyGeneralInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `g-nom_dev`.`assemblyGeneralInfo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `assemblyID` INT NOT NULL,
  `key` VARCHAR(400) NOT NULL,
  `value` VARCHAR(400) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `assemblyIDassemblyGeneralInfo_idx` (`assemblyID` ASC) VISIBLE,
  CONSTRAINT `assemblyIDassemblyGeneralInfo`
    FOREIGN KEY (`assemblyID`)
    REFERENCES `g-nom_dev`.`assembly` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `g-nom_dev`.`proteinFeatures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `g-nom_dev`.`proteinFeatures` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `proteinsID` INT NOT NULL,
  `path` VARCHAR(400) NOT NULL,
  `additionalFilesPath` VARCHAR(400) NULL,
  PRIMARY KEY (`id`),
  INDEX `proteinsIDfeatures_idx` (`proteinsID` ASC) VISIBLE,
  CONSTRAINT `proteinsIDfeatures`
    FOREIGN KEY (`proteinsID`)
    REFERENCES `g-nom_dev`.`proteins` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `g-nom_dev`.`analysisGeneralInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `g-nom_dev`.`analysisGeneralInfo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `analysisID` INT NOT NULL,
  `key` VARCHAR(400) NOT NULL,
  `value` VARCHAR(400) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `analysisIDGeneralInfo_idx` (`analysisID` ASC) VISIBLE,
  CONSTRAINT `analysisIDGeneralInfo`
    FOREIGN KEY (`analysisID`)
    REFERENCES `g-nom_dev`.`analysis` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `g-nom_dev`.`mapping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `g-nom_dev`.`mapping` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `assemblyID` INT NOT NULL,
  `path` VARCHAR(400) NOT NULL,
  `additionalFilesPath` VARCHAR(400) NULL,
  PRIMARY KEY (`id`),
  INDEX `assemblyIDMapping_idx` (`assemblyID` ASC) VISIBLE,
  CONSTRAINT `assemblyIDMapping`
    FOREIGN KEY (`assemblyID`)
    REFERENCES `g-nom_dev`.`assembly` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
